// =============================================================================
// Gainer Door Configurator — Structured Data
// Auto-generated from source Excel: "318 door information(3).xlsx"
// =============================================================================

// ---------------------------------------------------------------------------
// Type Definitions
// ---------------------------------------------------------------------------

export interface SizeLimits {
  minW: number | null;
  maxW: number | null;
  minH: number | null;
  maxH: number | null;
}

export interface Frame {
  code: string;
  doorType: string;
  allowedFillers: string[];
  standardFillers: string[];
  fillerThicknessLimit: number[];
  allowedFinishing: string[];
  specificColors: string[] | null;
  sizeLimits: SizeLimits;
  doorThickness: number | null;
  matchedHandle: string | null;
  matchedHardware: string | null;
  hardwareColors: string[];
  picture: string | null;
}

export interface Glass {
  code: string;
  name: string;
  type: 'glass';
  craft: string | null;
  craftCode: string | null;
  thicknesses: number[];
  silkScreen: boolean;
  pricingType: 'standard' | 'custom';
  priceSqm: number | null;
  picture: string | null;
}

export interface Leather {
  code: string;
  name: string;
  type: 'leather';
  thicknesses: number[];
  baseMaterial: 'Honeycomb Aluminum';
  pricingType: 'custom';
  picture: string | null;
}

export interface WoodVeneer {
  code: string;
  name: string;
  type: 'woodVeneer';
  thicknesses: number[];
  pricingType: 'custom';
  picture: string | null;
}

export interface QuartzStone {
  code: string;
  name: string;
  type: 'quartzStone';
  surface: string | null;
  thicknesses: number[];
  pricingType: 'custom';
  picture: string | null;
}

export type Filler = Glass | Leather | WoodVeneer | QuartzStone;

export interface SurfaceColor {
  code: string | null;
  name: string;
  picture: string | null;
}

export interface SurfaceFinishes {
  anodize: SurfaceColor[];
  spraySoftTouch: SurfaceColor[];
  sprayMetallic: SurfaceColor[];
}

export interface Hardware {
  code: string | null;
  name: string;
  allowedColors: string[];
  pricePerPiece: number | null;
  picture: string | null;
}

export interface Handle {
  code: string;
  name: string;
  surfaceFinishing: string | null;
  allowedColors: string[];
  picture: string | null;
}


// ---------------------------------------------------------------------------
// 1. Frames (Cabinet Doors)
// ---------------------------------------------------------------------------

export const frames: Frame[] = [
{
    code: 'GM004',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 500,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 28.2,
    matchedHandle: 'MK097',
    matchedHardware: 'top and bottom hinge(with gainer logo/without logo）',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM090',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 600,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 19.3,
    matchedHandle: 'routed handle(CNC)',
    matchedHardware: 'straight quick-install hinge/concealed quick-install hinge',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM023',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 500,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 24.0,
    matchedHandle: 'routed handle(CNC)',
    matchedHardware: 'heavy duty lift-off hinge/Hettich Sensys 8631i narrow frame concealed hinge/Blum CLIP top hinge 95°',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK118',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 350,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 30.0,
    matchedHandle: 'MK097',
    matchedHardware: 'top and bottom hinge(with gainer logo/without logo）',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK336',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 32.0,
    matchedHandle: 'MK097',
    matchedHardware: 'Hettich Sensys 8631i narrow frame concealed hinge',
    hardwareColors: ['black', 'silver'],
    picture: null,
  },
{
    code: 'GM054',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 35.0,
    matchedHandle: 'routed handle(CNC)',
    matchedHardware: 'RY-ZSJL-G pin hinge',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK162',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 35.0,
    matchedHandle: 'routed handle(CNC)',
    matchedHardware: 'RY-ZSJL-G pin hinge',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM106',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 27.5,
    matchedHandle: null,
    matchedHardware: 'top and bottom hinge(with gainer logo/without logo）',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK169',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 32.0,
    matchedHandle: 'routed handle(CNC)',
    matchedHardware: 'top and bottom hinge(with gainer logo/without logo）',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK073',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 1500,
    },
    doorThickness: 21.0,
    matchedHandle: 'recessed handle',
    matchedHardware: 'top and bottom hinge(with gainer logo/without logo）',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM073',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 22.0,
    matchedHandle: 'integrated  hidden door handle',
    matchedHardware: 'Blum hinge( 95° for thick doors)/Salice (Series 200 soft-close hinge 94°)',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM074',
    doorType: 'aluminum frame fiber/leather door',
    allowedFillers: ['leather'],
    standardFillers: [],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 28.0,
    matchedHandle: 'EM962E_128',
    matchedHardware: 'Blum hinge( 95° for thick doors)/Salice (Series 200 soft-close hinge 94°)',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM097',
    doorType: 'aluminum frame fiber/leather door',
    allowedFillers: ['leather'],
    standardFillers: [],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 25.0,
    matchedHandle: 'GNN2769A',
    matchedHardware: null,
    hardwareColors: [],
    picture: null,
  },
{
    code: 'GM072',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 29.0,
    matchedHandle: 'GM072-2-1',
    matchedHardware: 'RY-TDJL-ZXA heavy-duty top and bottom hinge',
    hardwareColors: ['black'],
    picture: null,
  },
{
    code: 'MK304',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 30.0,
    matchedHandle: null,
    matchedHardware: 'RY-TDJL-ZXA heavy-duty top and bottom hinge',
    hardwareColors: ['black'],
    picture: null,
  },
{
    code: 'GM060',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 30.0,
    matchedHandle: null,
    matchedHardware: 'RY-TDJL-ZXA heavy-duty top and bottom hinge',
    hardwareColors: ['black'],
    picture: null,
  },
{
    code: 'GM043',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 28.0,
    matchedHandle: null,
    matchedHardware: 'Salice CQ concealed wooden door hinge T12 (half overlay)',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM094',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 22.0,
    matchedHandle: 'GM094-2-C1L-SAGE',
    matchedHardware: 'Hettich 8631i narrow frame concealed hinge',
    hardwareColors: ['black', 'silver'],
    picture: null,
  },
{
    code: 'STM008',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [8],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 950,
      minH: null,
      maxH: null,
    },
    doorThickness: 38.0,
    matchedHandle: 'GF zinc alloy handle AGB 5085 Magnetic Mortise Lock Body + Cylinder',
    matchedHardware: 'JM470-1-2 top and bottom hinges',
    hardwareColors: ['black'],
    picture: null,
  },
{
    code: 'STM019',
    doorType: 'aluminum frame quartz stone door',
    allowedFillers: ['quartz stone'],
    standardFillers: [],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 900,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 56.0,
    matchedHandle: 'GNN2525-1A',
    matchedHardware: 'AN 172 3D',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK008',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [8],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 1200,
      maxW: 2400,
      minH: 1800,
      maxH: 3000,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: 'track and wheel',
    hardwareColors: [],
    picture: null,
  },
{
    code: 'MK165',
    doorType: 'aluminum frame glass pivot door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [8],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 1200,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 55.0,
    matchedHandle: null,
    matchedHardware: 'pivot accessory',
    hardwareColors: [],
    picture: null,
  },
{
    code: 'MK234',
    doorType: 'aluminum frame glass pivot door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [8],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 1200,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 55.0,
    matchedHandle: null,
    matchedHardware: 'pivot accessory',
    hardwareColors: [],
    picture: null,
  },
{
    code: 'YM002',
    doorType: 'aluminum frame glass slide door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [8],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 1200,
      maxW: 2400,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 45.0,
    matchedHandle: null,
    matchedHardware: 'track and wheel',
    hardwareColors: [],
    picture: null,
  },
{
    code: 'GM013',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 500,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 28.0,
    matchedHandle: null,
    matchedHardware: 'RY-ZSJL-F2 pin hinge (metal cover)',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM055',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 600,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 28.0,
    matchedHandle: null,
    matchedHardware: 'Salice CQ concealed wooden door hinge T12 (half overlay)',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM056',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 38.0,
    matchedHandle: null,
    matchedHardware: 'RY-ZSJL-G pin hinge',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM057',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 28.0,
    matchedHandle: 'GM047-3 GM047-4 GM047-5',
    matchedHardware: 'JL002-L&JL002-R top and bottom hinges',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM060',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 28.0,
    matchedHandle: null,
    matchedHardware: 'JL002-L&JL002-R top and bottom hinges',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'GM092',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: 22.0,
    matchedHandle: null,
    matchedHardware: 'concealed quick-install hinge',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK036',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 500,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 35.0,
    matchedHandle: 'GM047-3 GM047-4 GM047-5',
    matchedHardware: 'Pin hinge (Gainer style)',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK206',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 500,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 35.0,
    matchedHandle: null,
    matchedHardware: 'cup hinge',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK267',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G36'],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 500,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 28.0,
    matchedHandle: null,
    matchedHardware: 'JL002-L&JL002-R top and bottom hinges',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK007',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['tint glass', 'Wired Glass'],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 600,
      maxW: 1100,
      minH: 1800,
      maxH: 3000,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: null,
    hardwareColors: [],
    picture: null,
  },
{
    code: 'STM007',
    doorType: 'aluminum frame wood door',
    allowedFillers: ['wood veneer'],
    standardFillers: [],
    fillerThicknessLimit: [5],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: null,
      minH: null,
      maxH: null,
    },
    doorThickness: null,
    matchedHandle: 'zinc alloy single handle 5085 Magnetic Mortise Lock Body + Cylinder',
    matchedHardware: 'AN 160 3D Concealed Hinge',
    hardwareColors: ['black', 'gray'],
    picture: null,
  },
{
    code: 'MK010',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33'],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 350,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: 'top and bottom hinges',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK028',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33'],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 350,
      maxW: 600,
      minH: null,
      maxH: 3000,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: 'cup hinge',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK030',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33'],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 350,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: 'top and bottom hinges',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK032',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33'],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 350,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: 'top and bottom hinges',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK042',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33'],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 350,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: 'top and bottom hinges',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK054',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33'],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 350,
      maxW: 600,
      minH: null,
      maxH: 3000,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: 'cup hinge',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK106',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33'],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 350,
      maxW: 600,
      minH: null,
      maxH: 2700,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: 'top and bottom hinges',
    hardwareColors: ['black', 'gray', 'gold'],
    picture: null,
  },
{
    code: 'MK048',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33'],
    fillerThicknessLimit: [],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: 800,
      maxW: 1200,
      minH: 1800,
      maxH: 3000,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: null,
    hardwareColors: [],
    picture: null,
  },
{
    code: 'STM024',
    doorType: 'aluminum frame glass door',
    allowedFillers: ['glass'],
    standardFillers: [],
    fillerThicknessLimit: [8],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: null,
    sizeLimits: {
      minW: null,
      maxW: 1000,
      minH: null,
      maxH: 2700,
    },
    doorThickness: null,
    matchedHandle: null,
    matchedHardware: null,
    hardwareColors: [],
    picture: null,
  },
{
    code: 'MK133',
    doorType: 'mixed',
    allowedFillers: ['glass', 'quartz stone'],
    standardFillers: ['G01', 'G33'],
    fillerThicknessLimit: [4],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: ['PAD06', 'YPC03', 'PAN03', 'YPF01'],
    sizeLimits: {
      minW: 600,
      maxW: 1000,
      minH: null,
      maxH: 2800,
    },
    doorThickness: 45.0,
    matchedHandle: null,
    matchedHardware: null,
    hardwareColors: [],
    picture: null,
  },
{
    code: 'MK211',
    doorType: 'aluminum frame glass slide door',
    allowedFillers: ['glass'],
    standardFillers: ['G01', 'G33', 'G05', 'G34', 'Wired Glass'],
    fillerThicknessLimit: [8],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: ['PAD06', 'YPC03', 'PAN03', 'YPF01'],
    sizeLimits: {
      minW: 740,
      maxW: 1200,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 44.0,
    matchedHandle: null,
    matchedHardware: null,
    hardwareColors: [],
    picture: null,
  },
{
    code: 'MK234',
    doorType: 'aluminum frame glass slide door',
    allowedFillers: ['glass'],
    standardFillers: ['Jade Frosted Glass', 'Wired Glass'],
    fillerThicknessLimit: [8],
    allowedFinishing: ['anodize', 'spraySoftTouch', 'sprayMetallic'],
    specificColors: ['PAD06', 'YPD02', 'PAJ05', 'PAN03', 'YPN03', 'PAN05'],
    sizeLimits: {
      minW: 600,
      maxW: 1200,
      minH: null,
      maxH: 3000,
    },
    doorThickness: 50.0,
    matchedHandle: null,
    matchedHardware: null,
    hardwareColors: [],
    picture: null,
  }
];


// ---------------------------------------------------------------------------
// 2. Glass Fillers
// ---------------------------------------------------------------------------

export const glassList: Glass[] = [
{
    code: 'G01',
    name: 'Ultra-clear glass',
    type: 'glass',
    craft: null,
    craftCode: null,
    thicknesses: [3, 4, 5, 8],
    silkScreen: false,
    pricingType: 'standard',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G02',
    name: 'Ultra-clear single-sided jade sand laminated glass',
    type: 'glass',
    craft: 'Jade Sand & Laminated',
    craftCode: 'P0102',
    thicknesses: [8, 10],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G03',
    name: 'Ultra-clear double-sided jade sand glass',
    type: 'glass',
    craft: 'Jade Sand',
    craftCode: 'P01',
    thicknesses: [4],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G04',
    name: 'Ultra-clear laminated wired glass (FB-4-1)',
    type: 'glass',
    craft: 'Wired',
    craftCode: 'P03',
    thicknesses: [8, 9, 10],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G05',
    name: 'Ultra-clear single-sided jade sand laminated wired glass (FB-4-1)',
    type: 'glass',
    craft: 'Jade Sand & Wired',
    craftCode: 'P0103',
    thicknesses: [8, 10],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G06',
    name: 'Ultra-clear laminated wired glass (14 Grey)',
    type: 'glass',
    craft: 'Wired',
    craftCode: 'P03',
    thicknesses: [8, 10],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G07',
    name: 'Ultra-clear laminated wired glass (CH-709 Large Silver Mesh)',
    type: 'glass',
    craft: 'Wired',
    craftCode: 'P03',
    thicknesses: [8, 10],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G08',
    name: 'Ultra-clear single-sided jade sand laminated wired glass (6-709 Large Silver Mesh)',
    type: 'glass',
    craft: 'Jade Sand & Wired',
    craftCode: 'P0103',
    thicknesses: [8, 10],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G09',
    name: 'Ultra-clear small lamp core glass',
    type: 'glass',
    craft: 'Patterned',
    craftCode: 'P04',
    thicknesses: [5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G10',
    name: 'Ultra-clear Changhong glass',
    type: 'glass',
    craft: 'Patterned',
    craftCode: 'P04',
    thicknesses: [5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G11',
    name: 'Ultra-clear crystal glass',
    type: 'glass',
    craft: 'Patterned',
    craftCode: 'P04',
    thicknesses: [5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G12',
    name: 'Black striped glass',
    type: 'glass',
    craft: 'Patterned',
    craftCode: 'P04',
    thicknesses: [4, 5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G13',
    name: 'Ultra-clear water ripple glass',
    type: 'glass',
    craft: 'Patterned',
    craftCode: 'P04',
    thicknesses: [5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G14',
    name: 'Jade Kirin glass',
    type: 'glass',
    craft: 'Patterned',
    craftCode: 'P04',
    thicknesses: [5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G15',
    name: 'Ultra-clear silver glass',
    type: 'glass',
    craft: 'Patterned',
    craftCode: 'P04',
    thicknesses: [5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G16',
    name: 'Silk screen printed glass',
    type: 'glass',
    craft: 'Silk Screen Printing',
    craftCode: 'P05',
    thicknesses: [5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G17',
    name: 'Auspicious Cloud Pattern Silk Screen Glass',
    type: 'glass',
    craft: 'Silk Screen Printing',
    craftCode: 'P05',
    thicknesses: [5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G18',
    name: 'Ultra-clear Painted Changhong Glass',
    type: 'glass',
    craft: 'Spray Painting',
    craftCode: 'P06',
    thicknesses: [5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G19',
    name: 'Hexagonal Bamboo Weave Green Glass',
    type: 'glass',
    craft: 'Patterned',
    craftCode: 'P04',
    thicknesses: [8],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G20',
    name: 'Ultra-clear Single-sided High-transparency Frosted Glass (Matte Black)',
    type: 'glass',
    craft: 'Frosted & Coated',
    craftCode: 'P0708',
    thicknesses: [4],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G21',
    name: 'Ultra-clear Single-sided High-transparency Frosted Glass (Moroccan Blue)',
    type: 'glass',
    craft: 'Frosted & Coated',
    craftCode: 'P0708',
    thicknesses: [4],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G22',
    name: 'Ultra-clear Single-sided High-transparency Frosted Glass (London Grey)',
    type: 'glass',
    craft: 'Frosted & Coated',
    craftCode: 'P0708',
    thicknesses: [4],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G23',
    name: 'Ultra-clear Single-sided High-transparency Frosted Glass (Zephyr Red)',
    type: 'glass',
    craft: 'Frosted & Coated',
    craftCode: 'P0708',
    thicknesses: [4],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G24',
    name: 'Ultra-clear Single-sided High-transparency Frosted Glass (Aurora White)',
    type: 'glass',
    craft: 'Frosted & Coated',
    craftCode: 'P0708',
    thicknesses: [4],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G25',
    name: 'Ultra-clear laminated wired glass (B-12 Gold)',
    type: 'glass',
    craft: 'Wired & Patterned',
    craftCode: 'P0304',
    thicknesses: [8, 9, 10],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G26',
    name: 'Ultra-clear laminated wired glass (15800)',
    type: 'glass',
    craft: 'Wired',
    craftCode: 'P03',
    thicknesses: [8, 9, 10],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G27',
    name: 'European Grey laminated wired glass (B-14 Grey)',
    type: 'glass',
    craft: 'Wired',
    craftCode: 'P03',
    thicknesses: [8],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G28',
    name: 'Ultra-clear single-sided jade sand laminated wired glass (Y08-)',
    type: 'glass',
    craft: 'Jade Sand & Wired',
    craftCode: 'P0103',
    thicknesses: [8],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G29',
    name: 'Ultra-clear coated glass',
    type: 'glass',
    craft: 'Coated',
    craftCode: 'P08',
    thicknesses: [5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G30',
    name: 'Grey tinted glass',
    type: 'glass',
    craft: null,
    craftCode: null,
    thicknesses: [4, 5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G31',
    name: 'Golden tinted glass',
    type: 'glass',
    craft: null,
    craftCode: null,
    thicknesses: [4, 5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G32',
    name: 'Golden tinted coated glass',
    type: 'glass',
    craft: null,
    craftCode: null,
    thicknesses: [5],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G33',
    name: 'European Grey Glass',
    type: 'glass',
    craft: null,
    craftCode: null,
    thicknesses: [4, 5, 8],
    silkScreen: false,
    pricingType: 'standard',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G34',
    name: 'European Grey Double-sided Jade Sand Glass',
    type: 'glass',
    craft: 'Jade Sand',
    craftCode: 'P01',
    thicknesses: [4],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G35',
    name: 'European Grey Double-sided Jade Sand Laminated Glass',
    type: 'glass',
    craft: 'Jade Sand & Laminated',
    craftCode: 'P0102',
    thicknesses: [8],
    silkScreen: false,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G36',
    name: 'Transparent Black Glass',
    type: 'glass',
    craft: null,
    craftCode: null,
    thicknesses: [4],
    silkScreen: false,
    pricingType: 'standard',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G37',
    name: 'Ultra-clear Silk Screen Printed Roman Grey Glass',
    type: 'glass',
    craft: 'Silk Screen Printing',
    craftCode: 'P05',
    thicknesses: [4, 5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G38',
    name: 'Grey Glass Silk Screen Printed Roman Grey Glass',
    type: 'glass',
    craft: 'Silk Screen Printing',
    craftCode: 'P05',
    thicknesses: [4, 5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G39',
    name: 'Ultra-clear Coated Silk Screen Printed Roman Grey Glass',
    type: 'glass',
    craft: 'Silk Screen Printing & Coated',
    craftCode: 'P0508',
    thicknesses: [5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G40',
    name: 'Ultra-clear Silk Screen Printed Antique Bronze Glass',
    type: 'glass',
    craft: 'Silk Screen Printing',
    craftCode: 'P05',
    thicknesses: [3, 4, 5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G41',
    name: 'Grey Glass Silk Screen Printed Antique Bronze Glass',
    type: 'glass',
    craft: 'Silk Screen Printing',
    craftCode: 'P05',
    thicknesses: [4, 5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G42',
    name: 'Golden Tinted Coated Silk Screen Printed Antique Bronze Glass',
    type: 'glass',
    craft: 'Silk Screen Printing & Coated',
    craftCode: 'P0508',
    thicknesses: [5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G43',
    name: 'Ultra-clear Silk Screen Printed Brass Color Glass',
    type: 'glass',
    craft: 'Silk Screen Printing',
    craftCode: 'P05',
    thicknesses: [3, 4, 5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  },
{
    code: 'G44',
    name: 'Grey Glass Silk Screen Printed Brass Color Glass',
    type: 'glass',
    craft: 'Silk Screen Printing',
    craftCode: 'P05',
    thicknesses: [4, 5],
    silkScreen: true,
    pricingType: 'custom',
    priceSqm: null,
    picture: null,
  }
];


// ---------------------------------------------------------------------------
// 3. Leather Fillers (baseMaterial: Honeycomb Aluminum)
// ---------------------------------------------------------------------------

export const leatherList: Leather[] = [
{
    code: 'H64144',
    name: 'Lychee grain PU',
    type: 'leather',
    thicknesses: [1],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'H64148',
    name: 'Lychee grain PU',
    type: 'leather',
    thicknesses: [1],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'H64151',
    name: 'Lychee grain PU',
    type: 'leather',
    thicknesses: [1],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'H64160',
    name: 'Lychee grain PU',
    type: 'leather',
    thicknesses: [1],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'H76008',
    name: 'Lychee grain PU',
    type: 'leather',
    thicknesses: [1],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'H76009',
    name: 'Lychee grain PU',
    type: 'leather',
    thicknesses: [1],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'B76009',
    name: 'Lamb grain PU',
    type: 'leather',
    thicknesses: [0.6],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'H76014',
    name: 'Lychee grain PU',
    type: 'leather',
    thicknesses: [1],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'B76014',
    name: 'Lamb grain PU',
    type: 'leather',
    thicknesses: [0.6],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'H76015',
    name: 'Lychee grain PU',
    type: 'leather',
    thicknesses: [1],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'B76015',
    name: 'Lamb grain PU',
    type: 'leather',
    thicknesses: [0.6],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'H76016',
    name: 'Lychee grain PU',
    type: 'leather',
    thicknesses: [1],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'B76016',
    name: 'Lamb grain PU',
    type: 'leather',
    thicknesses: [0.6],
    baseMaterial: 'Honeycomb Aluminum',
    pricingType: 'custom',
    picture: null,
  }
];


// ---------------------------------------------------------------------------
// 4. Wood Veneer Fillers
// ---------------------------------------------------------------------------

export const woodVeneerList: WoodVeneer[] = [
{
    code: 'O7AR',
    name: 'O7AR',
    type: 'woodVeneer',
    thicknesses: [8, 18, 25],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'S154',
    name: 'S154',
    type: 'woodVeneer',
    thicknesses: [12, 18, 25, 35],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'FA84',
    name: 'FA84',
    type: 'woodVeneer',
    thicknesses: [18],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'LS14',
    name: 'LS14',
    type: 'woodVeneer',
    thicknesses: [12, 18, 25, 35],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'S133',
    name: 'S133',
    type: 'woodVeneer',
    thicknesses: [18],
    pricingType: 'custom',
    picture: null,
  },
{
    code: '75V',
    name: '75V',
    type: 'woodVeneer',
    thicknesses: [12, 18, 25],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'F641',
    name: 'F641',
    type: 'woodVeneer',
    thicknesses: [18],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'FC18',
    name: 'FC18',
    type: 'woodVeneer',
    thicknesses: [18],
    pricingType: 'custom',
    picture: null,
  },
{
    code: '036W',
    name: '036W',
    type: 'woodVeneer',
    thicknesses: [8, 18, 25],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'UA92',
    name: 'UA92',
    type: 'woodVeneer',
    thicknesses: [18],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'U727',
    name: 'U727',
    type: 'woodVeneer',
    thicknesses: [12, 18, 25],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'P204',
    name: 'P204',
    type: 'woodVeneer',
    thicknesses: [18],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'C351',
    name: 'C351',
    type: 'woodVeneer',
    thicknesses: [8, 18, 25],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'C028',
    name: 'C028',
    type: 'woodVeneer',
    thicknesses: [8, 18, 25],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'P205',
    name: 'P205',
    type: 'woodVeneer',
    thicknesses: [18],
    pricingType: 'custom',
    picture: null,
  }
];


// ---------------------------------------------------------------------------
// 5. Quartz Stone Fillers
// ---------------------------------------------------------------------------

export const quartzStoneList: QuartzStone[] = [
{
    code: 'QS-001',
    name: 'Silk blanco',
    type: 'quartzStone',
    surface: '(Matte Silky Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-002',
    name: 'Silk vison',
    type: 'quartzStone',
    surface: '(Matte Silky Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-003',
    name: 'Amaranto natural',
    type: 'quartzStone',
    surface: '(Matte Silky Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-004',
    name: 'Muschio natural',
    type: 'quartzStone',
    surface: '(Matte Silky Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-005',
    name: 'Syros',
    type: 'quartzStone',
    surface: '(Matte Silky Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-006',
    name: 'Larsen',
    type: 'quartzStone',
    surface: '(Premium Blanco White - Grey Vein Natural Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-007',
    name: 'Storm',
    type: 'quartzStone',
    surface: '(Grey Natural Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-008',
    name: 'Azalai',
    type: 'quartzStone',
    surface: '(Matte Silky Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-009',
    name: 'Iseo',
    type: 'quartzStone',
    surface: '(Hammered Base Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-010',
    name: 'Jasper',
    type: 'quartzStone',
    surface: '(Mocha Mixed Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-011',
    name: 'Fusion',
    type: 'quartzStone',
    surface: '(Rainbow Natural Surface)',
    thicknesses: [6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-012',
    name: 'Masai',
    type: 'quartzStone',
    surface: '(Pedrera Natural Surface)',
    thicknesses: [4, 6],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-013',
    name: 'Matte Snowfield White',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [6, 12],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-014',
    name: 'Light Grey Base Matte Great Wall Grey · Zinc Grey',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [3.5],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-015',
    name: 'Khaki Base  Matte Dunhuang Yellow · Sand Color',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [3.5],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-016',
    name: 'Dark Green Base Matte Bamboo Sea Green · Indigo Green',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [3.5],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-017',
    name: 'Matte Twilight Snow White',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [3.5, 6, 12],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-018',
    name: 'Dark Green Base Glossy Green Mist',
    type: 'quartzStone',
    surface: 'Base Gloss',
    thicknesses: [6, 12],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-019',
    name: 'Matte Ink White',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [6, 12],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-020',
    name: 'Matte Volcanic Rock',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [3.5, 6, 12],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-021',
    name: 'Matte Storm Black',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [6, 12],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-022',
    name: 'Matte Off-white',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [3.5],
    pricingType: 'custom',
    picture: null,
  },
{
    code: 'QS-023',
    name: 'Matte Coffee Color',
    type: 'quartzStone',
    surface: 'Matte',
    thicknesses: [3.5],
    pricingType: 'custom',
    picture: null,
  }
];


// ---------------------------------------------------------------------------
// 6. Surface Finishes
// ---------------------------------------------------------------------------

export const surfaceFinishes: SurfaceFinishes = {
  anodize: [
{
      code: 'YPF01',
      name: 'Fine sandblasted  matte black',
      picture: null,
    },
{
      code: 'YPC03',
      name: 'Fine sandblasted  silver-white',
      picture: null,
    },
{
      code: 'YPD02',
      name: 'Fine sandblasted  Roman gray',
      picture: null,
    },
{
      code: 'YLR07',
      name: 'Brushed iron gray',
      picture: null,
    },
{
      code: 'YLJ08',
      name: 'Brushed champagne',
      picture: null,
    },
{
      code: 'YLN06',
      name: 'Brushed antique bronze',
      picture: null,
    },
{
      code: 'YPN03',
      name: 'Fine sandblasted  antique bronze',
      picture: null,
    },
{
      code: 'YPJ06',
      name: 'Fine sandblasted champagne',
      picture: null,
    },
{
      code: 'YLF01',
      name: 'Brushed matte black',
      picture: null,
    },
{
      code: 'YLB09',
      name: 'Brushed light luxury gold',
      picture: null,
    },
{
      code: 'YLF03',
      name: 'Brushed bright black',
      picture: null,
    },
{
      code: 'YLC03',
      name: 'Brushed silver-white',
      picture: null,
    },
{
      code: 'YLD04',
      name: 'Brushed Roman gray',
      picture: null,
    },
{
      code: null,
      name: 'Oxidized Brushed Light Gold (SAGE Custom Gold)',
      picture: null,
    },
{
      code: null,
      name: 'Oxidized Sandblasted Light Champagne 06 (Customer Color Code: C-32)',
      picture: null,
    }
  ],
  spraySoftTouch: [
{
      code: 'PAE06',
      name: 'Aurora white',
      picture: null,
    },
{
      code: 'PAM02',
      name: 'Egyptian Beige',
      picture: null,
    },
{
      code: 'PAD21',
      name: 'London Gray',
      picture: null,
    },
{
      code: 'PAD30',
      name: 'Roman Gray',
      picture: null,
    },
{
      code: 'PAD26',
      name: 'Hamilton Steel',
      picture: null,
    },
{
      code: 'PAE09',
      name: 'Cors White',
      picture: null,
    },
{
      code: 'PAJ14',
      name: 'Ottawa Khaki',
      picture: null,
    },
{
      code: 'PAI02',
      name: 'Lake Green',
      picture: null,
    },
{
      code: 'PAD22',
      name: 'Brazilian Cocoa',
      picture: null,
    },
{
      code: 'PAD28',
      name: 'Volcanic Ash',
      picture: null,
    },
{
      code: 'PAU03',
      name: 'Chepur Red',
      picture: null,
    },
{
      code: 'PAAA02',
      name: 'Moroccan Blue',
      picture: null,
    },
{
      code: 'PAF09',
      name: 'Matte Black',
      picture: null,
    }
  ],
  sprayMetallic: [
{
      code: 'PAE02',
      name: 'High Gloss White',
      picture: null,
    },
{
      code: 'PAF01',
      name: 'Matte Black',
      picture: null,
    },
{
      code: 'PAB09',
      name: 'Light Luxury Gold',
      picture: null,
    },
{
      code: 'PAN07',
      name: 'Light Luxury Copper',
      picture: null,
    },
{
      code: 'PAJ04',
      name: 'Champagne Gold',
      picture: null,
    },
{
      code: 'PAD29',
      name: 'Hamilton Steel',
      picture: null,
    },
{
      code: 'PAN04',
      name: 'Bronze Gold',
      picture: null,
    },
{
      code: 'PAD16',
      name: 'Volcanic Ash Gray',
      picture: null,
    },
{
      code: 'PAO01',
      name: 'Shiny Silver Khaki',
      picture: null,
    },
{
      code: 'PAU01',
      name: 'China Red',
      picture: null,
    },
{
      code: 'PAD18',
      name: 'Cream Beige',
      picture: null,
    },
{
      code: 'PAD24',
      name: 'Light Cloud Gold',
      picture: null,
    },
{
      code: 'PAN03',
      name: 'Antique Bronze Gold',
      picture: null,
    },
{
      code: 'PAR01',
      name: 'Iron Gray',
      picture: null,
    },
{
      code: 'PAD17',
      name: 'Graphite Gray',
      picture: null,
    },
{
      code: 'PAD06',
      name: 'Cement Gray',
      picture: null,
    },
{
      code: 'PAJ13',
      name: 'Champagne Pink Gold',
      picture: null,
    },
{
      code: 'PAJ05',
      name: 'Champagne Coffee Gold',
      picture: null,
    },
{
      code: 'PAJ02',
      name: 'Champagne Green Gold',
      picture: null,
    },
{
      code: 'PAD09',
      name: 'Titanium Gold Gray',
      picture: null,
    },
{
      code: 'PAD10',
      name: 'Glacier Gray',
      picture: null,
    },
{
      code: 'PAN05',
      name: 'Light Luxury Khaki',
      picture: null,
    },
{
      code: 'PAAA01',
      name: 'Bruce Blue',
      picture: null,
    },
{
      code: 'PAY02',
      name: 'Cocoa Red',
      picture: null,
    },
{
      code: 'PAD11',
      name: 'Alaska Gold',
      picture: null,
    },
{
      code: 'PAD12',
      name: 'Beach Gold',
      picture: null,
    }
  ],
};


// ---------------------------------------------------------------------------
// 7. Hardware (Hinges & Accessories)
// ---------------------------------------------------------------------------

export const hardwareList: Hardware[] = [
{
    code: 'HG-JL002',
    name: 'JL002-L/JL002-R Pivot Hinge',
    allowedColors: ['black', 'gray', 'gold'],
    pricePerPiece: 120,
    picture: null,
  },
{
    code: 'HG-JL006',
    name: 'JL006-L/JL006-R Pivot Hinge',
    allowedColors: ['black', 'gray', 'gold'],
    pricePerPiece: 120,
    picture: null,
  },
{
    code: 'HG-A21',
    name: 'Type A Pin Hinge with Plastic Cover (2.1)',
    allowedColors: ['black', 'gray', 'gold'],
    pricePerPiece: 220,
    picture: null,
  },
{
    code: 'HG-SEN',
    name: 'Sensys 8638i Concealed Quick-assembly Hinge (Full Overlay/ Half Overlay/ Inset Hinge)',
    allowedColors: ['black', 'silver'],
    pricePerPiece: 78,
    picture: null,
  },
{
    code: 'HG-RYF2',
    name: 'RY-ZSJL-F2 Pin Hinge (Metal Cover)',
    allowedColors: ['black', 'grey', 'gold'],
    pricePerPiece: 220,
    picture: null,
  },
{
    code: 'HG-RYG',
    name: 'RY-ZSJL-G Pin Hinge',
    allowedColors: ['black', 'grey', 'gold'],
    pricePerPiece: 220,
    picture: null,
  },
{
    code: null,
    name: 'Gainer CQ hinges',
    allowedColors: [],
    pricePerPiece: 100,
    picture: null,
  },
{
    code: null,
    name: 'Heavy duty top and bottom hinge',
    allowedColors: [],
    pricePerPiece: 180,
    picture: null,
  },
{
    code: null,
    name: 'electric rotating shaft',
    allowedColors: [],
    pricePerPiece: 5148,
    picture: null,
  },
{
    code: null,
    name: 'manual rotating shaft',
    allowedColors: [],
    pricePerPiece: 3168,
    picture: null,
  },
{
    code: null,
    name: 'single track',
    allowedColors: [],
    pricePerPiece: 264,
    picture: null,
  },
{
    code: null,
    name: 'double track',
    allowedColors: [],
    pricePerPiece: 440,
    picture: null,
  },
{
    code: null,
    name: 'hanging wheel',
    allowedColors: [],
    pricePerPiece: 330,
    picture: null,
  },
{
    code: 'HG-BLUM',
    name: 'Bailong 110°Quick-assembly Hinge (Full Overlay/ Half Overlay/ Inset Hinge)',
    allowedColors: ['black', 'silver'],
    pricePerPiece: null,
    picture: null,
  },
{
    code: 'HG-SLCQ',
    name: 'Salichi-CQ Concealed Wooden Door Hinge T12 (Half Overlay)',
    allowedColors: ['black', 'grey', 'gold'],
    pricePerPiece: null,
    picture: null,
  },
{
    code: null,
    name: 'Pipe Hinge（salichi/blum）',
    allowedColors: [],
    pricePerPiece: null,
    picture: null,
  },
{
    code: null,
    name: 'JM668-1 Hinge Base Sleeve',
    allowedColors: [],
    pricePerPiece: null,
    picture: null,
  },
{
    code: null,
    name: 'JM668-2 Zinc Alloy Hinge Base Sleeve',
    allowedColors: [],
    pricePerPiece: null,
    picture: null,
  }
];


// ---------------------------------------------------------------------------
// 8. Handles
// ---------------------------------------------------------------------------

export const handleList: Handle[] = [
{
    code: 'GM047-3',
    name: 'GM047-3',
    surfaceFinishing: null,
    allowedColors: [],
    picture: null,
  },
{
    code: 'GM047-4',
    name: 'GM047-4',
    surfaceFinishing: null,
    allowedColors: [],
    picture: null,
  },
{
    code: 'GM047-5',
    name: 'GM047-5',
    surfaceFinishing: null,
    allowedColors: [],
    picture: null,
  },
{
    code: 'MK092-8A(slide door handle A)',
    name: 'MK092-8A(slide door handle A)',
    surfaceFinishing: null,
    allowedColors: [],
    picture: null,
  },
{
    code: 'GNN1629',
    name: '19板G型拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1630',
    name: '20板G型拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1631',
    name: '21板G型拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA284',
    name: '19板G型拉手 （带堵头）',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA285',
    name: '20板G型拉手 （带堵头）',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA286',
    name: '21板G型拉手 （带堵头）',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA233',
    name: '免防撞条 免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2705-A',
    name: '免防撞条 免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA1318',
    name: '不带防撞条 免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA232',
    name: '带防撞条 16板免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2457',
    name: '不带防撞条 16板免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2522',
    name: '不带防撞条 18板免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'L100',
    name: 'C型免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'L101',
    name: 'L型免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN817',
    name: '地柜柜体上拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN818',
    name: '地柜柜体中拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN878',
    name: '竖装免拉手铝材 （双侧）',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1616',
    name: '竖装免拉手铝材 （单侧）',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2530',
    name: '双边带灯免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2531',
    name: '单边带灯免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2649-1',
    name: '水平L型免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2649-2',
    name: '水平C型免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2649-3',
    name: '高柜L型免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2649-4',
    name: '高柜C型免拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM002',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA1214',
    name: '封边拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM935',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM031',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM046',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM049',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM095',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM102',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM197',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM136',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM923',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM929',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM930',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM942A',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM942B',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN204',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA896',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1027',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1096',
    name: '明装拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA1205',
    name: '子母拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA1216',
    name: '子母拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1193',
    name: '子母拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1195',
    name: '子母拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2420',
    name: '子母拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2421',
    name: '子母拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2718',
    name: '子母拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2719',
    name: '子母拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1826',
    name: '封边拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1838',
    name: '拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2668-A',
    name: '拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN678',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1220',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1039',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN782',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN783',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN677',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2701-1-A',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN749',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN306',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1047',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2476',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2704',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1645',
    name: '铣型定尺拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2376-1',
    name: '斜口拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2376-2',
    name: '斜口拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2376-3',
    name: '斜口拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2667-1',
    name: '拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN648',
    name: '拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN647',
    name: '拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA126',
    name: '拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA130',
    name: '拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA132',
    name: '拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1033',
    name: '拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM932-A',
    name: '内嵌拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM987-A',
    name: '内嵌拉手',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM604',
    name: 'EM604',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN2108',
    name: 'GNN2108',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'GNN1465',
    name: 'GNN1465',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM445B-430',
    name: 'EM445B-430',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM918B-893',
    name: 'EM918B-893',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM763B',
    name: 'EM763B',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'CNN1538-585',
    name: 'CNN1538-585',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EM885',
    name: 'EM885',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'CNN1539-585',
    name: 'CNN1539-585',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA1259',
    name: 'EA1259',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA061A',
    name: 'EA061A',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA159',
    name: 'EA159',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  },
{
    code: 'EA146',
    name: 'EA146',
    surfaceFinishing: 'anodizing /  spray painting',
    allowedColors: ['color swatch colors'],
    picture: null,
  }
];


// ---------------------------------------------------------------------------
// 9. Filler Lookup Map (for state machine filtering)
// ---------------------------------------------------------------------------

export const fillerMap = {
  glass: glassList,
  leather: leatherList,
  woodVeneer: woodVeneerList,
  quartzStone: quartzStoneList,
};


// ---------------------------------------------------------------------------
// 10. State-Machine Filtering Logic
// ---------------------------------------------------------------------------

export function getAvailableFrames(w: number, h: number): (Frame & { disabled: boolean })[] {
  return frames.map((frame) => {
    const { minW, maxW, minH, maxH } = frame.sizeLimits;
    const disabled =
      (minW !== null && w < minW) ||
      (maxW !== null && w > maxW) ||
      (minH !== null && h < minH) ||
      (maxH !== null && h > maxH);
    return { ...frame, disabled };
  });
}

export function getAvailableFinishes(frame: Frame): SurfaceFinishes {
  const allowed = frame.allowedFinishing;
  return {
    anodize: allowed.includes('anodize') ? [...surfaceFinishes.anodize] : [],
    spraySoftTouch: allowed.includes('spraySoftTouch') ? [...surfaceFinishes.spraySoftTouch] : [],
    sprayMetallic: allowed.includes('sprayMetallic') ? [...surfaceFinishes.sprayMetallic] : [],
  };
}

export function getAvailableFillers(frame: Frame) {
  const allowedTypes = frame.allowedFillers;
  const thicknessLimit = frame.fillerThicknessLimit;

  const result: Filler[] = [];

  if (allowedTypes.includes('glass')) {
    for (const g of glassList) {
      const validThicknesses = thicknessLimit.length > 0
        ? g.thicknesses.filter((t) => thicknessLimit.includes(t))
        : g.thicknesses;
      if (validThicknesses.length > 0) {
        result.push({ ...g, thicknesses: validThicknesses });
      }
    }
  }

  if (allowedTypes.includes('leather')) {
    result.push(...leatherList);
  }

  if (allowedTypes.includes('wood veneer') || allowedTypes.includes('woodVeneer')) {
    result.push(...woodVeneerList);
  }

  if (allowedTypes.includes('quartz stone') || allowedTypes.includes('quartzStone')) {
    result.push(...quartzStoneList);
  }

  return result;
}

export function getMatchedHandle(frame: Frame): Handle | null {
  if (!frame.matchedHandle) return null;
  const handleName = frame.matchedHandle.toLowerCase();
  return (handleList.find(
    (h) => h.code.toLowerCase() === handleName || h.name.toLowerCase() === handleName
  ) ?? null) as Handle | null;
}

export function getMatchedHandles(frame: Frame): Handle[] {
  if (!frame.matchedHandle) return [];
  const raw = frame.matchedHandle;
  const codes = raw.split(/[\n\/]/).map((s) => s.trim().toLowerCase()).filter(Boolean);
  return handleList.filter(
    (h) => codes.some((c) => h.code.toLowerCase() === c || h.name.toLowerCase().includes(c))
  );
}

export function calculateHingeQty(heightMm: number): { qty: number; usePivot: boolean } {
  if (heightMm <= 2000) return { qty: 2, usePivot: false };
  if (heightMm <= 2500) return { qty: 4, usePivot: false };
  return { qty: 0, usePivot: true };
}
